name: {{artifactId}}

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: {{artifactId}}-app
    env_file:
      - .env
    ports:
      - "8080:8080"
{{composeAppDependsOn}}
{{composeDbService}}
{{composeVolumesSection}}
