package dev.springrad.core;

import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.ConnectException;
import java.net.UnknownHostException;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpTimeoutException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.time.Duration;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

public final class InitializrClient implements ProjectGenerator {
    private static final Duration REQUEST_TIMEOUT = Duration.ofSeconds(10);

    private final HttpClient httpClient;
    private final URI baseUri;

    public InitializrClient() {
        this(URI.create("https://start.spring.io"));
    }

    public InitializrClient(URI baseUri) {
        this(HttpClient.newBuilder().connectTimeout(REQUEST_TIMEOUT).build(), baseUri);
    }

    InitializrClient(HttpClient httpClient, URI baseUri) {
        this.httpClient = httpClient;
        this.baseUri = baseUri;
    }

    @Override
    public GenerationResult generate(ProjectConfig config) {
        URI uri = buildRequestUri(config);
        HttpRequest request = HttpRequest.newBuilder(uri)
                .GET()
                .timeout(REQUEST_TIMEOUT)
                .build();

        try {
            HttpResponse<byte[]> response = httpClient.send(request, HttpResponse.BodyHandlers.ofByteArray());
            if (response.statusCode() != 200) {
                String body = new String(response.body(), StandardCharsets.UTF_8);
                throw new InitializrApiException(response.statusCode(), body);
            }

            Path zipPath = Files.createTempFile("springrad-initializr-", ".zip");
            Files.write(zipPath, response.body());
            extractZip(zipPath, config.outputDirectory());
            Files.deleteIfExists(zipPath);

            List<String> topLevelEntries = listTopLevel(config.outputDirectory());
            return new GenerationResult(config.outputDirectory(), topLevelEntries);
        } catch (HttpTimeoutException e) {
            throw new InitializrTimeoutException("Request to Spring Initializr timed out after 10s", e);
        } catch (IOException e) {
            if (e instanceof ConnectException || e instanceof UnknownHostException) {
                throw new InitializrTimeoutException("Could not connect to Spring Initializr", e);
            }
            throw new GenerationIOException("Failed to generate project from Spring Initializr", e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new SpringRadException(
                    "Initializr request was interrupted",
                    "Project generation was interrupted. Please retry.",
                    e
            );
        }
    }

    URI buildRequestUri(ProjectConfig config) {
        Map<String, String> params = new LinkedHashMap<>();
        params.put("groupId", config.groupId());
        params.put("artifactId", config.artifactId());
        params.put("name", config.name());
        params.put("description", "Generated by springrad");
        params.put("packageName", packageName(config.groupId(), config.artifactId()));
        params.put("javaVersion", config.javaVersion());
        if (config.bootVersion() != null && !config.bootVersion().isBlank() && !"latest".equals(config.bootVersion())) {
            params.put("bootVersion", config.bootVersion());
        }
        params.put("packaging", config.packaging().name());
        params.put("type", config.buildTool() == ProjectConfig.BuildTool.gradle ? "gradle-project" : "maven-project");
        if (config.dependencies() != null && !config.dependencies().isEmpty()) {
            params.put("dependencies", String.join(",", config.dependencies()));
        }

        String query = params.entrySet().stream()
                .map(entry -> url(entry.getKey()) + "=" + url(entry.getValue()))
                .collect(Collectors.joining("&"));

        return URI.create(baseUri.toString() + "/starter.zip?" + query);
    }

    private static String packageName(String groupId, String artifactId) {
        return groupId + "." + artifactId.replace('-', '.');
    }

    private static String url(String value) {
        return URLEncoder.encode(value, StandardCharsets.UTF_8);
    }

    private static void extractZip(Path zipPath, Path outputDir) throws IOException {
        Files.createDirectories(outputDir);
        try (ZipInputStream zis = new ZipInputStream(Files.newInputStream(zipPath))) {
            ZipEntry entry;
            while ((entry = zis.getNextEntry()) != null) {
                Path target = outputDir.resolve(entry.getName()).normalize();
                if (!target.startsWith(outputDir.normalize())) {
                    throw new GenerationIOException(
                            "Unsafe zip entry: " + entry.getName(),
                            "Received an invalid archive from Initializr.",
                            null
                    );
                }

                if (entry.isDirectory()) {
                    Files.createDirectories(target);
                } else {
                    Files.createDirectories(target.getParent());
                    Files.copy(zis, target, StandardCopyOption.REPLACE_EXISTING);
                    markExecutableIfWrapper(target);
                }
                zis.closeEntry();
            }
        }
    }

    private static void markExecutableIfWrapper(Path target) {
        String fileName = target.getFileName().toString();
        if ("gradlew".equals(fileName) || "mvnw".equals(fileName)) {
            target.toFile().setExecutable(true, false);
        }
    }

    private static List<String> listTopLevel(Path outputDirectory) throws IOException {
        try (var stream = Files.list(outputDirectory)) {
            return stream
                    .map(path -> path.getFileName().toString())
                    .sorted(Comparator.naturalOrder())
                    .toList();
        }
    }
}
