spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
{{messagingProdConfig}}

server:
  error:
    include-stacktrace: never
    include-message: never

logging:
  level:
    root: WARN
    {{packageName}}: INFO

{{jwtSecretConfig}}
